"""web demo calls: optional lead, channel

Revision ID: 6195d5637593
Revises: b5342ef81de9
Create Date: 2026-08-15 09:25:35.719271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6195d5637593"
down_revision: str | None = "b5342ef81de9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows, which are all phone calls; the
    # default is then dropped so the application stays the source of truth.
    op.add_column(
        "calls",
        sa.Column("channel", sa.String(length=10), nullable=False, server_default="phone"),
    )
    op.alter_column("calls", "channel", server_default=None)
    op.add_column("calls", sa.Column("visitor_name", sa.String(length=200), nullable=True))
    op.alter_column("calls", "lead_id", existing_type=sa.UUID(), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("calls", "lead_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("calls", "visitor_name")
    op.drop_column("calls", "channel")
    # ### end Alembic commands ###
