"""initial schema

Revision ID: b5342ef81de9
Revises:
Create Date: 2026-08-15 08:12:59.387150

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5342ef81de9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("dnc", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_phone"), "leads", ["phone"], unique=True)
    op.create_table(
        "calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("provider_call_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "ringing",
                "in_progress",
                "completed",
                "failed",
                "no_answer",
                "busy",
                name="call_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("recording_path", sa.String(length=500), nullable=True),
        sa.Column("agent_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calls_lead_id"), "calls", ["lead_id"], unique=False)
    op.create_table(
        "qualifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("intent", sa.String(length=500), nullable=True),
        sa.Column("geography", sa.String(length=500), nullable=True),
        sa.Column("budget", sa.String(length=500), nullable=True),
        sa.Column("timeline", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("sentiment", sa.String(length=50), nullable=True),
        sa.Column("disposition", sa.String(length=50), nullable=True),
        sa.Column("next_action", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qualifications_call_id"), "qualifications", ["call_id"], unique=True)
    op.create_table(
        "turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("t_offset_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turns_call_id"), "turns", ["call_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turns_call_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index(op.f("ix_qualifications_call_id"), table_name="qualifications")
    op.drop_table("qualifications")
    op.drop_index(op.f("ix_calls_lead_id"), table_name="calls")
    op.drop_table("calls")
    op.drop_index(op.f("ix_leads_phone"), table_name="leads")
    op.drop_table("leads")
    # ### end Alembic commands ###
